### ISSUE TITLE
signature grid does not contract and expand when browser does in chrome

### ISSUE THREAD

**Issue by jamesrobb** [piratar/safetyvalve#1]

**Comment by koddsson** [comment]
Can you expand on this? It's not quite clear to me what the expected behaviour is and what the bug is. What is signature grid?

**Comment by jamesrobb** [comment]
If you drill down to a petition detail page, you will see a grid of signatures. If you attempt to resize your browser window while using chrome, the behaviour isn't quite as expected.

Does that make sense?

**Comment by koddsson** [comment]
Thanks! I'll try to take a look at this soon-ish.

**Comment by jamesrobb** [comment]
I think we might opt for another solution to this particular component, though not sure when exactly. I think it will depend on when we move to another design and such.

**Comment by jamesrobb** [comment]
Stale issue.
