### ISSUE TITLE
ventill.is login redirects to skilriki.is loginerror page.

### ISSUE THREAD

**Issue by busla** [piratar/safetyvalve#14]
I´m positive that I logged in to www.ventill.is just a few days ago and voted but now /minarsidur takes me to http://innskraning.island.is/LoginError.html. It took me to the island.is login page before.

Has something changed in the last few days?

**Comment by busla** [comment]
Hmm.. seems to be an issue with island.is. Can´t log in there either.

**Comment by busla** [comment]
Might have something to do with Auðkenni, charging for their electronic auth system 5 days ago:
http://www.ruv.is/frett/rukka-fyrir-rafraen-skilriki-fra-aramotum

**Comment by jamesrobb** [comment]
Hmm, I will look into this. Hopefully it's nothing. I have cc'ed Helgi too.

//-- James Robb
//-- +354.666.0887 (Iceland/Ísland)

**Comment by busla** [comment]
Seems to be my IP. I only get the error page on devices behind my router.

Curious what island.is did to my IP :-P

**Comment by busla** [comment]
I´ll ask island.is to look into what is happening since this might have something to do with too many api requests or something.
