### ISSUE TITLE
Users receives a 403 CSFR verfication failed.

### ISSUE THREAD

**Issue by jamesrobb** [piratar/safetyvalve#4]
![10363309_10152397729769028_224619641_o](https://cloud.githubusercontent.com/assets/3089512/2978465/dc6f6326-dbb9-11e3-9e92-fcc28936cb25.jpg)

This errors happens after someone clicks 'sign/oppose/mótmæla', is brought to icekey (or other verification source), and then is brought to the form that prompts for an initial e-mail and to confirm it. After clicking confirm on this page (to store the initial e-mail and receive a receipt), the form that was generated with the two e-mail fields (email and confirm e-mail) generates this error.

initial e-mail refers to the fact that after authenticating for the first time with icekey, there is still no e-mail stored for the user. The system will always prompt at this stage for an e-mail if none is stored in the database for that user.

**Comment by busla** [comment]
Could you add the csrf token to a cookie instead, since you are being redirected back from island.is?

https://github.com/busla/safetyvalve/blob/python3/safetyvalve/petition/static/petition/js/petition.js#L35-L44

**Comment by jamesrobb** [comment]
Stale issue.
