### ISSUE TITLE
Feature request: Petitions for the people

### ISSUE THREAD

**Issue by kfridjonsson** [piratar/safetyvalve#6]
As per instructions from James I add this as a issue since there seems to be no real feature request venue.

It would be highly benefitial to the public to be able to set up verifiable petitions to the government or other official agencies. Having it under the flag og Öryggisventill would be an extra value for everybody since more people would get to know and hopefully use it as a platform.

kfridjonsson

**Comment by bjornlevi** [comment]
That's what betraisland.is is for

**Comment by jamesrobb** [comment]
A possibility one day, but pretty far down the pipeline.
