### ISSUE TITLE
Roadmap and goals of the project

### ISSUE THREAD

**Issue by busla** [piratar/safetyvalve#7]
Would be great to see a draft of a roadmap of the project and it´s goals. I think it would help with getting developers on board. 

For instance, I would like to contribute a REST api to lay the grounds for a mobile app. Users can then be fed notifiactions with new bills, which will increase engagement.

I´m willing to be committed but I would really like to have some idea about the future of the project.

**Comment by helgihg** [comment]
Yes, at the moment we're quite unsure about precisely that. The
Icelandic government has now put up a website for petitions with digital
signatures so the project's purpose and status is quite uncertain at the
moment.

**Comment by busla** [comment]
Ok,

Is it in production?

**Comment by helgihg** [comment]
I don't follow. Is what in production?

**Comment by busla** [comment]
Sorry, I ment the parliament bill voting project you mentioned.

**Comment by busla** [comment]
I guess this is out of the scope of this project so I will close the ticket :-)

**Comment by busla** [comment]
Re-opening this ticket.

Just took a look at the government´s petition project (GPP). It´s of completely different nature than SV. 

How I see it, SV has so much potential in giving people a (pseudo) voice in every legal bill that is being proposed. It gives them an overview of what´s happening at the parliament and what law might govern them and their children in the future. 

To me, GPP is just a general petition web app with legit authorisation. People can start lists and share them. But that´s it.

I think SV is the start of something beautiful, but what it needs is more engagement. Solving that issue is another question :-)

Back to the original request. It would be great see where you want to take the project.

**Comment by jamesrobb** [comment]
A roadmap will be published eventually. Not sure when, but it's very very slowly in the works. I would expect the production from Helgi and I to come in highly concentrated bursts.
